import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--use-angle=vulkan', '--enable-features=Vulkan', '--ignore-gpu-blocklist', '--enable-gpu'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
await p.addInitScript(() => { let a = 12345; Math.random = () => { a |= 0; a = a + 0x6D2B79F5 | 0; let t = Math.imul(a ^ a >>> 15, 1 | a); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; }; });
p.on('pageerror', (e) => console.log('pageerror', e.message));
await p.goto(process.argv[2] || 'http://localhost:4173');
await p.waitForFunction(() => window.game?.ui && document.querySelector('.btn-play'), null, { timeout: 120000 });
const r = await p.evaluate(async () => {
  const g = window.game;
  g.startMatch({ heroId: 'sera' });
  g.ai.setPlayerAutoplay?.(true);
  // fast-forward to 6 min without render
  g.renderer.setAnimationLoop(null);
  const rr = g.renderer.render.bind(g.renderer), comp = g.composer;
  g.renderer.render = () => {}; g.composer = null; g.fixedDt = 0.05;
  for (let i = 0; i < 6 * 60 * 20; i++) g.tick();
  g.renderer.render = rr; g.composer = comp; g.fixedDt = undefined;
  const mid = g.heroes.find(h => h.team === 'sunward' && h.lane === 'mid') ?? g.player.hero;
  g.cameraCtl.focus(mid.position.x, mid.position.z, true);
  const T = {};
  const wrap = (name, obj, fn) => { const o = obj[fn].bind(obj); obj[fn] = (...a) => { const t = performance.now(); const res = o(...a); T[name] = (T[name] ?? 0) + performance.now() - t; return res; }; };
  for (const s of ['ai','rules','projectiles','abilities','items','world','vfx','cameraCtl','input','audio','ui']) if (g[s]?.update) wrap(s, g[s], 'update');
  const origTick = g.tick.bind(g);
  let unitT = 0;
  if (g.composer) wrap('render(composer)', g.composer, 'render'); else wrap('render', g.renderer, 'render');
  wrap('tickTotal', g, 'tick');
  const U = Object.getPrototypeOf(Object.getPrototypeOf(g.player.hero));
  const H = Object.getPrototypeOf(g.player.hero);
  let modelT = 0;
  const upd = U.update; U.update = function (dt) { const t = performance.now(); upd.call(this, dt); T.unitUpdate = (T.unitUpdate ?? 0) + performance.now() - t; };
  const hupd = H.update; H.update = function (dt) { const t = performance.now(); hupd.call(this, dt); T.heroUpdate = (T.heroUpdate ?? 0) + performance.now() - t; };
  const sep = U.separate; U.separate = function (o, dt) { const t = performance.now(); sep.call(this, o, dt); T.separate = (T.separate ?? 0) + performance.now() - t; };
  const wrapModels = () => { for (const u of g.units) if (u.model && !u.model._w) { const mu = u.model.update.bind(u.model); u.model._w = 1; u.model.update = (dt) => { const t = performance.now(); mu(dt); T.modelUpdate = (T.modelUpdate ?? 0) + performance.now() - t; }; } };
  wrapModels(); setInterval(wrapModels, 500);
  const uir = g.unitsInRadius.bind(g); g.unitsInRadius = (...a) => { const t = performance.now(); const r = uir(...a); T.unitsInRadius = (T.unitsInRadius ?? 0) + performance.now() - t; return r; };
  g.renderer.setAnimationLoop(() => g.tick());
  const f0 = g.frame, t0 = performance.now();
  await new Promise(r => setTimeout(r, 8000));
  const frames = g.frame - f0, secs = (performance.now() - t0) / 1000;
  const out = { fps: +(frames / secs).toFixed(1), units: g.units.filter(u=>u.alive).length };
  for (const k in T) out[k] = +(T[k] / frames).toFixed(2);
  // draw call info with plain render
  g.renderer.info.autoReset = false; g.renderer.info.reset(); rr(g.scene, g.camera);
  out.calls = g.renderer.info.render.calls; out.tris = g.renderer.info.render.triangles; g.renderer.info.autoReset = true;
  out.programs = g.renderer.info.programs?.length; out.geometries = g.renderer.info.memory.geometries; out.textures = g.renderer.info.memory.textures;
  out.quality = localStorage.getItem('throneshard.world.quality');
  const R = g.renderer; const fin = () => R.getContext().finish();
  const time = (fn) => { fn(); fin(); const t = performance.now(); for (let i = 0; i < 10; i++) fn(); fin(); return +((performance.now() - t) / 10).toFixed(2); };
  out.updMatrixWorld = time(() => g.scene.updateMatrixWorld());
  let objs = 0, skinned = 0, bones = 0; g.scene.traverse(o => { objs++; if (o.isSkinnedMesh) { skinned++; bones += o.skeleton.bones.length; } });
  Object.assign(out, { objs, skinned, bones });
  out.rawRender = time(() => rr(g.scene, g.camera));
  R.shadowMap.autoUpdate = false; out.rawNoShadowUpdate = time(() => rr(g.scene, g.camera)); R.shadowMap.autoUpdate = true;
  const fr = new g.THREE.Frustum().setFromProjectionMatrix(new g.THREE.Matrix4().multiplyMatrices(g.camera.projectionMatrix, g.camera.matrixWorldInverse));
  const groups = {};
  const tag = (o) => { let x = o; while (x) { if (x.userData?.unit) return 'unit:' + x.userData.unit.kind + ':' + (x.userData.unit.modelKind); if (x.parent === g.scene) return 'top:' + (x.name || x.type); x = x.parent; } return 'orphan'; };
  g.scene.traverseVisible(o => { if ((o.isMesh || o.isPoints || o.isLine || o.isSprite)) { if (!o.frustumCulled || (o.geometry && (o.geometry.boundingSphere || o.geometry.computeBoundingSphere(), fr.intersectsObject(o)))) { const k = tag(o); groups[k] = (groups[k] ?? 0) + 1; } } });
  out.meshGroups = Object.entries(groups).sort((a,b)=>b[1]-a[1]).slice(0, 25);
  out.composerSync = time(() => comp.render(0.016));
  const P = g.world.post;
  P.bloom.enabled = false; out.cNoBloom = time(() => comp.render(0.016));
  P.smaa.enabled = false; out.cNoBloomSmaa = time(() => comp.render(0.016));
  P.grade.enabled = false; out.cRenderOutputOnly = time(() => comp.render(0.016));
  P.bloom.enabled = true; P.smaa.enabled = true; P.grade.enabled = true;
  out.rawAgain = time(() => rr(g.scene, g.camera));
  out.composerAgain = time(() => comp.render(0.016));
  return out;
});
console.log(JSON.stringify(r, null, 1));
await b.close();
