const $ = id => document.getElementById(id);

export const dom = {
  app: $('app'),
  thermal: $('thermal'),
  tint: $('thermalTint'),
  chip: $('withitness'),
  chipTxt: $('wTxt'),
  labels: $('tells'),
  touch: $('touch'),
  touchKeys: $('touchKeys'),
  touchHint: $('touchHint'),
  kbdKeys: $('kbdKeys'),
  menu: $('menu'),
  log: $('log'),
  pa: $('pa'),
  paTitle: $('paTitle'),
  paTxt: $('paTxt'),
  clock: $('tClock'),
  zone: $('zone'),
  hyper: $('hyper'),
  tempV: $('tempV'),
  tempS: $('tempS'),
  tempBox: $('roomtemp'),
  hazardBox: $('hazardBox'),
  hazardKey: $('hazardKey'),
  hazardV: $('hazardV'),
  hazardS: $('hazardS'),
  cfu: $('cfu'),
  lesson: $('lesson'),
  lsUnit: $('lsUnit'),
  lsCount: $('lsCount'),
  lsLabel: $('lsLabel'),
  lsLine: $('lsLine'),
  lsBar: $('lsBar'),
  lsMark: $('lsMark'),
  cbTitle: $('cbTitle'),
  cbRoom: $('cbRoom'),
  observation: $('observation'),
  obsRows: $('obsRows'),
  startScreen: $('startScreen'),
  startSub: $('startSub'),
  startDay: $('startDay'),
  startAdmin: $('startAdmin'),
  startOver: $('startOver'),
  startBtn: $('startBtn'),
  seedRow: $('seedRow'),
  seedLabel: $('seedLabel'),
  seedInput: $('seedInput'),
  seedBtn: $('seedBtn'),
  seedHint: $('seedHint'),
  chartScreen: $('seatingScreen'),
  chartTitle: $('chartTitle'),
  chartSub: $('chartSub'),
  chartIntro: $('chartIntro'),
  chartPlan: $('chartPlan'),
  chartSide: $('chartSide'),
  chartConfirm: $('chartConfirm'),
  chartReset: $('chartReset'),
  endScreen: $('endScreen'),
  endTitle: $('endTitle'),
  endSub: $('endSub'),
  endBody: $('endBody'),
  confScreen: $('conferenceScreen'),
  confTitle: $('confTitle'),
  confSub: $('confSub'),
  confPrompt: $('confPrompt'),
  confOptions: $('confOptions'),
  meters: {
    mastery: [$('bMas'), $('vMas')],
    fidelity: [$('bFid'), $('vFid')],
    rapport: [$('bRap'), $('vRap')],
    bandwidth: [$('bBan'), $('vBan')]
  }
};
