import { dom } from './dom.js';

// Phase 8 — the controls, on screen.
//
// UI only: it takes rows in and calls back out (CLAUDE.md). It does not know
// what an action does, which of them the rubric wants today, or that a hold
// costs Bandwidth. It knows there are chips and there are pads.
//
// The rows are generated by main.js from CFG.keys, so a new key is a button
// without an edit here. A key with no label in data/controls.json still gets a
// chip — with its own action name on it, which is ugly and visible, and that is
// the right failure: a missing label should look missing.
//
// Two pads can be down at once. That is the whole reason these are pointer
// events with capture rather than clicks: the five-second wait-time hold has to
// survive a thumb also holding Withitness, and it has to release even if the
// finger drifts off the pad before it lifts.
export function createTouchControls({ copy, chips, holds, onPress, onHold }) {
  // The one-line "how this works" is NOT in here. Every edge of a phone screen
  // is already spoken for — it collided with the clipboard, the rubric panel,
  // the hold pads and the toast log in turn — and it is a thing you read once,
  // before the bell. It lives on the start card instead (index.html's
  // #touchHint), which main.js fills from the same copy deck.
  const chipHTML = rows => rows.map(r =>
    `<button class="tchip" data-act="${r.action}" title="${r.long || ''}">` +
    `<b>${r.short}</b><em>${r.code || ''}</em></button>`).join('');

  const main = chips.filter(c => !c.action.startsWith('look:'));
  const look = chips.filter(c => c.action.startsWith('look:'));

  dom.touch.innerHTML =
    `<div id="stickPad"><i></i></div>` +
    `<div id="touchTray" class="hide">` +
      `<div class="tth">${copy.tray.title}<span>${copy.tray.note}</span></div>` +
      `<div class="ttchips">${chipHTML(look)}</div>` +
    `</div>` +
    `<div id="touchBar">` +
      chipHTML(main) +
      (look.length ? `<button class="tchip tray" data-tray="1"><b>${copy.tray.open}</b><em>${look.length}</em></button>` : '') +
    `</div>` +
    `<div id="touchHolds">` +
      holds.map(h =>
        `<button class="tpad" data-hold="${h.name}" title="${h.long || ''}">` +
        `<b>${h.short}</b></button>`).join('') +
    `</div>`;

  const pad = dom.touch.querySelector('#stickPad');
  const knob = pad.querySelector('i');
  const tray = dom.touch.querySelector('#touchTray');
  // Looked up once. setHoldState is called every frame.
  const padEls = new Map([...dom.touch.querySelectorAll('.tpad')].map(el => [el.dataset.hold, el]));

  dom.touch.addEventListener('pointerdown', e => {
    const chip = e.target.closest('.tchip');
    if (chip) {
      e.preventDefault();
      if (chip.dataset.tray) { tray.classList.toggle('hide'); chip.classList.toggle('open'); return; }
      chip.classList.add('lit');
      setTimeout(() => chip.classList.remove('lit'), 180);
      onPress(chip.dataset.act);
      return;
    }
    const held = e.target.closest('.tpad');
    if (!held) return;
    e.preventDefault();
    held.setPointerCapture(e.pointerId);
    held.classList.add('down');
    onHold(held.dataset.hold, true);
  });

  const release = e => {
    const held = e.target.closest ? e.target.closest('.tpad') : null;
    if (!held) return;
    held.classList.remove('down');
    onHold(held.dataset.hold, false);
  };
  dom.touch.addEventListener('pointerup', release);
  dom.touch.addEventListener('pointercancel', release);

  return {
    // The stick is drawn where the thumb landed, not where a designer put a
    // circle. `at` is null when the thumb lifts.
    setStick(at) {
      if (!at) { pad.classList.remove('on'); return; }
      pad.classList.add('on');
      pad.style.left = at.x + 'px';
      pad.style.top = at.y + 'px';
      // 38% of the pad's own width is the knob's throw, so the drawn stick
      // reaches its edge at exactly the tilt CFG.touch.stickRadius calls full.
      knob.style.left = (50 + at.dx * 38) + '%';
      knob.style.top = (50 + at.dy * 38) + '%';
    },
    // Withitness can be turned on by SHIFT on a machine that also has a
    // touchscreen, and the pad has to agree with the room.
    setHoldState(name, on) {
      const el = padEls.get(name);
      if (el) el.classList.toggle('active', !!on);
    },
    show(on) { dom.touch.classList.toggle('on', !!on); }
  };
}
