#!/usr/bin/env node
// tools/make-gallery.mjs — bake the front door's three schools into a file.
//
//   node tools/make-gallery.mjs            write js/gallerystock.js
//   node tools/make-gallery.mjs --check    say whether it is up to date, write nothing
//
// The gallery cards are finished schools, and a finished school is a share
// payload — the same deflate-raw'd, base64url'd string Phase 9 puts after a
// `#`. Nothing about it needs a server, and nothing about it needs a build
// step either: this runs when the recipes in `gallery.js` change, and its
// output is committed like any other source file.
//
// Everything here that decides anything lives in `gallery.js` — the recipes,
// the thumbnail reduction, the counted facts. This file is the crank: build
// each recipe, serialize it the way the Share dialog serializes, encode it the
// way share.js encodes, and print the result as a module. `--check` is what
// CI would run if it ever wanted to catch a stale stock file; the suite
// already catches a *wrong* one, which is the failure that matters.

import { writeFile, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CARDS, stockEntry, cardTitle, factLine } from '../js/gallery.js';
import { buildSchool } from '../js/generate.js';
import { serialize } from '../js/save-load.js';
import { encodeShare } from '../js/share.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'js', 'gallerystock.js');

// The Share dialog's own omissions, for the same reasons: a tracing image and
// imported model files are megabytes and neither belongs in a string. A
// generated school has neither, so this is a statement of the contract rather
// than a saving — the card and the link carry the same design.
const SHARE_OPTS = { omitOverlay: true, omitModels: true };

const HEAD = `// gallerystock.js — the front door's schools, as bytes.
//
// GENERATED by tools/make-gallery.mjs. Do not edit: change a recipe in
// gallery.js and run the tool again.
//
// Each payload is a share.js string — the same one the Share dialog puts after
// a '#' — so opening a card is exactly opening a link somebody sent you, minus
// the somebody. The thumbnails are geometry rather than images (planThumb), and
// the facts are counted off the design rather than typed.
//
// This module is fetched lazily, the first time the welcome opens. A load that
// never shows the welcome never pays for it.
`;

async function build() {
  const entries = [];
  for (const card of CARDS) {
    const state = buildSchool({ ...card.brief });
    const payload = await encodeShare(serialize(state, SHARE_OPTS));
    const entry = { ...stockEntry(state), payload };
    entries.push({ card, entry });
  }
  return entries;
}

function render(entries) {
  const rows = entries.map(({ card, entry }) => {
    const rooms = entry.thumb.rooms
      .map((r) => `      { c: '${r.c}', p: ${JSON.stringify(r.p)} },`)
      .join('\n');
    return `  // ${cardTitle(card)} — ${factLine(entry.facts)}\n`
      + `  ${card.id}: {\n`
      + `    facts: ${JSON.stringify(entry.facts)},\n`
      + `    thumb: {\n`
      + `      w: ${entry.thumb.w}, h: ${entry.thumb.h},\n`
      + `      rooms: [\n${rooms}\n      ],\n`
      + `    },\n`
      + `    payload: '${entry.payload}',\n`
      + `  },`;
  });
  return `${HEAD}\nexport const STOCK = {\n${rows.join('\n')}\n};\n`;
}

const entries = await build();
const text = render(entries);

if (process.argv.includes('--check')) {
  const have = await readFile(OUT, 'utf8').catch(() => '');
  const same = have === text;
  console.log(same ? 'gallerystock.js is up to date' : 'gallerystock.js is stale — run the tool');
  process.exit(same ? 0 : 1);
}

await writeFile(OUT, text);
const kb = (n) => `${Math.round(n / 102.4) / 10} KB`;
for (const { card, entry } of entries) {
  console.log(`${cardTitle(card).padEnd(22)} ${factLine(entry.facts).padEnd(44)} ${kb(entry.payload.length)}`);
}
console.log(`\nwrote js/gallerystock.js — ${kb(text.length)}`);
