// textures.js — the texture registry and the resolution tier, with no THREE in it.
//
// materials.js used to hold MATS and load each file straight off the registry.
// Phase 4 split the registry out so bare Node can read it: test/smoke-textures.mjs
// walks every file MATS names, in every tier, and fails when one is missing on
// disk — the check that would have caught a 1k set generated for eight of nine
// surfaces. The tier heuristic lives here for the same reason: it is a function
// of numbers, so it is tested as one.
//
// Two tiers on disk (README, "Textures"):
//   textures/<key>/<slug>_<map>_2k.jpg       the Poly Haven 2K files as downloaded
//   textures/<key>/1k/<slug>_<map>_1k.jpg    generated by tools/make-textures.mjs
// The 1k filenames are Poly Haven's own 1K names, so a hand-downloaded 1K set
// drops into the same folder and the registry never has to name a tier twice.

// key → { polyhaven slug, repeat, files{diff,normal,rough|arm}, placeholder params }
// References the exact Poly Haven 2K filenames as downloaded (no renaming).
// Two map layouts exist in the set:
//   • diff/rough sets:  <slug>_diff_2k.jpg (+ _nor_gl_2k, _rough_2k)
//   • ARM sets:         <slug>_arm_2k.jpg packs AO (R), roughness (G),
//     metalness (B) into one texture — wired to all three material slots.
// brown_leather ships "albedo" instead of "diff"; the registry just lists
// each file explicitly so naming quirks don't matter.
export const MATS = {
  floorWood: {
    polyhaven: "wood_floor_deck", repeat: [6, 4], color: 0x6b4a2e, rough: 0.8,
    files: { diff: "wood_floor_deck_diff_2k.jpg", normal: "wood_floor_deck_nor_gl_2k.jpg", arm: "wood_floor_deck_arm_2k.jpg" },
  },
  wallPlaster: {
    polyhaven: "painted_plaster_wall", repeat: [4, 2], color: 0x3a2c20, rough: 0.95,
    files: { diff: "painted_plaster_wall_diff_2k.jpg", normal: "painted_plaster_wall_nor_gl_2k.jpg", arm: "painted_plaster_wall_arm_2k.jpg" },
  },
  wallBrick: {
    polyhaven: "red_brick_plaster_patch_02", repeat: [5, 2], color: 0x59352a, rough: 0.9,
    files: { diff: "red_brick_plaster_patch_02_diff_2k.jpg", normal: "red_brick_plaster_patch_02_nor_gl_2k.jpg", rough: "red_brick_plaster_patch_02_rough_2k.jpg" },
  },
  barTop: {
    polyhaven: "dark_wooden_planks", repeat: [4, 1], color: 0x2e1d10, rough: 0.35,
    files: { diff: "dark_wooden_planks_diff_2k.jpg", normal: "dark_wooden_planks_nor_gl_2k.jpg", arm: "dark_wooden_planks_arm_2k.jpg" },
  },
  tableTop: {
    polyhaven: "wood_table_001", repeat: [1, 1], color: 0x50361f, rough: 0.5,
    files: { diff: "wood_table_001_diff_2k.jpg", normal: "wood_table_001_nor_gl_2k.jpg", rough: "wood_table_001_rough_2k.jpg" },
  },
  ceiling: {
    polyhaven: "concrete_wall_008", repeat: [6, 4], color: 0x191411, rough: 1.0,
    files: { diff: "concrete_wall_008_diff_2k.jpg", normal: "concrete_wall_008_nor_gl_2k.jpg", arm: "concrete_wall_008_arm_2k.jpg" },
  },
  kitchenTile: {
    polyhaven: "wood_planks", repeat: [3, 2], color: 0x8c8478, rough: 0.6,
    files: { diff: "wood_planks_diff_2k.jpg", normal: "wood_planks_nor_gl_2k.jpg", arm: "wood_planks_arm_2k.jpg" },
  },
  leather: {
    polyhaven: "brown_leather", repeat: [1, 1], color: 0x4a2f1d, rough: 0.65,
    files: { diff: "brown_leather_albedo_2k.jpg", normal: "brown_leather_nor_gl_2k.jpg", rough: "brown_leather_rough_2k.jpg" },
  },
  metal: {
    polyhaven: "brushed_concrete", repeat: [1, 1], color: 0x7a7f85, rough: 0.4, metal: 0.7,
    files: { diff: "brushed_concrete_diff_2k.jpg", normal: "brushed_concrete_nor_gl_2k.jpg", rough: "brushed_concrete_rough_2k.jpg" },
  },
};

/** The tiers that exist on disk, smallest first. "2k" is the registry's own
 *  filename; every other tier is a folder beside it. */
export const TIERS = ["1k", "2k"];
/** The tier every surface downloads when nothing argues for more. */
export const DEFAULT_TIER = "1k";

/** Every (key, file) pair the registry names — 27 today. One entry per file
 *  the loader will fetch, so a count of these is the count the loading line
 *  shows. */
export function textureFiles() {
  const out = [];
  for (const [key, def] of Object.entries(MATS)) {
    for (const [slot, file] of Object.entries(def.files || {})) out.push({ key, slot, file });
  }
  return out;
}

/** Path of one registry file at one tier, relative to the project root.
 *  "floorWood", "wood_floor_deck_diff_2k.jpg", "1k" →
 *  "textures/floorWood/1k/wood_floor_deck_diff_1k.jpg". The 2k file is the
 *  registry name unchanged, in the folder itself. */
export function texturePath(key, file, tier = DEFAULT_TIER) {
  if (!TIERS.includes(tier)) throw new Error(`no such texture tier: ${tier}`);
  if (tier === "2k") return `textures/${key}/${file}`;
  if (!/_2k\.[a-z]+$/.test(file)) throw new Error(`not a 2k registry filename: ${file}`);
  return `textures/${key}/${tier}/${file.replace(/_2k(\.[a-z]+)$/, `_${tier}$1`)}`;
}

/**
 * Which tier this device should download. A pure function of the facts the
 * caller can read, so the rule is one place and testable:
 *
 *  • `override` (the `?tex=` query) wins outright when it names a tier on disk,
 *    so a measurement or an eyeball comparison can ask for either.
 *  • `saveData` (navigator.connection.saveData) forces 1k: the user asked.
 *  • Otherwise 2k only when it would show and the GPU can hold it: a device
 *    pixel ratio of 2 or more, a texture limit of 8192 or more, and a
 *    backing-store width of at least 2560 device pixels — a Retina laptop or
 *    a 4K desktop. A phone at dpr 3 with a 1170 px backing store is 1k: the
 *    room is 60 m of fog away from ever showing a 2k texel on it, and 66 MB is
 *    a real price on a phone.
 *  • Everything else is 1k.
 */
export function pickTier({ override, saveData = false, dpr = 1, maxTextureSize = 4096, widthPx = 0 } = {}) {
  if (override && TIERS.includes(override)) return override;
  if (saveData) return "1k";
  const d = Number.isFinite(dpr) ? dpr : 1;
  const max = Number.isFinite(maxTextureSize) ? maxTextureSize : 0;
  const w = Number.isFinite(widthPx) ? widthPx : 0;
  if (d >= 2 && max >= 8192 && w >= 2560) return "2k";
  return DEFAULT_TIER;
}
