// Generated by tools/service-worker.mjs. Do not edit by hand — run
// `npm run build` in Numina/ and commit what it writes.
//
// The offline kit. An event is a weekend in a field with no signal, so every
// page of this site, both stylesheets, every script, the five fonts and
// Pagefind's loader are put on the device the first time a browser visits.
//
// VERSION is a hash over the bytes of everything in the list below except
// Pagefind's, which is not stable across machines. It changes when the site
// changes and only then, so an unchanged rebuild produces this file unchanged
// and CI's rebuild check stays quiet.
const VERSION = "1eb923d6c179";
const CACHE = `numina-${VERSION}`;
const SCOPE = "/Numina/";

const PRECACHE = [
  "/Numina/",
  "/Numina/assets/favicon.svg",
  "/Numina/assets/social-card.png",
  "/Numina/css/main.css",
  "/Numina/css/print.css",
  "/Numina/fonts/alegreya-latin-400-italic.woff2",
  "/Numina/fonts/alegreya-latin-400-normal.woff2",
  "/Numina/fonts/alegreya-sc-latin-400-normal.woff2",
  "/Numina/fonts/grenze-gotisch-latin-500-normal.woff2",
  "/Numina/fonts/grenze-gotisch-latin-700-normal.woff2",
  "/Numina/js/build-rules.js",
  "/Numina/js/build-state.js",
  "/Numina/js/build-view.js",
  "/Numina/js/builder.js",
  "/Numina/js/offline.js",
  "/Numina/js/packet.js",
  "/Numina/js/skill-filter.js",
  "/Numina/js/theme.js",
  "/Numina/lore/",
  "/Numina/lore/characters/",
  "/Numina/lore/glossary/",
  "/Numina/lore/history/",
  "/Numina/lore/nations/",
  "/Numina/lore/nations/aluvair/",
  "/Numina/lore/nations/dovenost/",
  "/Numina/lore/nations/five-duchies/",
  "/Numina/lore/nations/kindaria/",
  "/Numina/lore/nations/konnigstrava/",
  "/Numina/lore/nations/ldahn-linenation/",
  "/Numina/lore/nations/melluria/",
  "/Numina/lore/nations/merrigor/",
  "/Numina/lore/nations/mists-of-eltiel/",
  "/Numina/lore/nations/myos-islands/",
  "/Numina/lore/nations/ophrailes/",
  "/Numina/lore/nations/principalities-of-the-reach/",
  "/Numina/lore/nations/rues/",
  "/Numina/lore/nations/spyndelmere/",
  "/Numina/lore/nations/tbarris/",
  "/Numina/lore/nations/vale-of-scyllina/",
  "/Numina/lore/notable-figures/",
  "/Numina/lore/peoples/",
  "/Numina/lore/realms/",
  "/Numina/lore/religion/",
  "/Numina/lore/travel-commerce/",
  "/Numina/lore/world/",
  "/Numina/mechanics/",
  "/Numina/mechanics/building-a-character/",
  "/Numina/mechanics/character-builder/",
  "/Numina/mechanics/combat-reference/",
  "/Numina/mechanics/core-rules/",
  "/Numina/mechanics/crafting/",
  "/Numina/mechanics/etiquette-safety/",
  "/Numina/mechanics/new-players/",
  "/Numina/mechanics/packet/",
  "/Numina/mechanics/skills/",
  "/Numina/mechanics/skills/all-skills/",
  "/Numina/mechanics/skills/aspects/",
  "/Numina/mechanics/skills/attributes-vitality/",
  "/Numina/mechanics/skills/cultures/",
  "/Numina/mechanics/skills/domains/",
  "/Numina/mechanics/skills/excellencies/",
  "/Numina/mechanics/skills/expressions/",
  "/Numina/mechanics/skills/foundations/",
  "/Numina/mechanics/skills/hidden-excellencies-expressions/",
  "/Numina/mechanics/skills/open-skills/",
  "/Numina/mechanics/weapon-construction/",
  "/Numina/new-to-numina/",
  "/Numina/new-to-numina/community-and-etiquette/",
  "/Numina/new-to-numina/day-in-the-life/",
  "/Numina/new-to-numina/faq/",
  "/Numina/new-to-numina/npcing/",
  "/Numina/new-to-numina/quick-reference/",
  "/Numina/new-to-numina/story-so-far/",
  "/Numina/new-to-numina/what-to-pack/",
  "/Numina/pagefind/pagefind-entry.json",
  "/Numina/pagefind/pagefind-ui.css",
  "/Numina/pagefind/pagefind-ui.js",
  "/Numina/pagefind/pagefind.js",
  "/Numina/pagefind/wasm.en.pagefind",
  "/Numina/pagefind/wasm.unknown.pagefind",
  "/Numina/search/",
];

// Pagefind needs one more file before it can answer anything: the language
// metadata chunk, whose name carries a content hash. That hash is not stable
// across machines, so it cannot be written into the list above — it is read out
// of pagefind-entry.json at install time instead. The index chunks and result
// fragments underneath it are fetched as a search needs them and land in the
// same cache through the runtime path below, so search works offline for what
// has been searched for online at least once.
async function pagefindMeta() {
  try {
    const entry = await fetch(`${SCOPE}pagefind/pagefind-entry.json`, { cache: "reload" });
    if (!entry.ok) return [];
    const data = await entry.json();
    return Object.values(data.languages ?? {})
      .map((lang) => lang.hash)
      .filter(Boolean)
      .map((hash) => `${SCOPE}pagefind/pagefind.${hash}.pf_meta`);
  } catch {
    return [];
  }
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      const urls = PRECACHE.concat(await pagefindMeta());
      // Not cache.addAll: it rejects the whole list if any single response is
      // not ok, which would leave a visitor with no kit at all because one file
      // 404'd. Each failure costs its own file and nothing else.
      await Promise.all(
        urls.map((url) =>
          cache.add(new Request(url, { cache: "reload" })).catch(() => {})
        )
      );
      // No skipWaiting here. A new build takes over when the reader presses the
      // button that says so, not underneath a page they are reading.
    })()
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) {
        if (key.startsWith("numina-") && key !== CACHE) await caches.delete(key);
      }
      await self.clients.claim();
    })()
  );
});

// Cache first, then refresh in the background: the field case has to answer
// from the device without waiting for a network that is not there, and a
// half-bar of signal is slower than no signal at all. Freshness is the
// version's job, not this handler's.
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(SCOPE)) return;
  event.respondWith(respond(event));
});

async function respond(event) {
  const request = event.request;
  const cache = await caches.open(CACHE);
  // ignoreSearch, so /mechanics/packet/?p=new-player is served by the copy of
  // /mechanics/packet/ that is already on the device.
  const cached = await cache.match(request, { ignoreSearch: true });
  const network = fetch(request)
    .then((response) => {
      if (response && response.ok && response.type === "basic") {
        cache.put(request, response.clone()).catch(() => {});
      }
      return response;
    })
    .catch(() => null);
  if (cached) {
    event.waitUntil(network);
    return cached;
  }
  const fresh = await network;
  if (fresh) return fresh;
  if (request.mode === "navigate") {
    const home = await cache.match(SCOPE);
    if (home) return home;
  }
  return new Response("This page is not in the copy of Numina saved on this device.", {
    status: 503,
    headers: { "content-type": "text/plain; charset=utf-8" },
  });
}

self.addEventListener("message", (event) => {
  const data = event.data ?? {};
  const reply = (message) => {
    if (event.ports && event.ports[0]) event.ports[0].postMessage(message);
    else if (event.source) event.source.postMessage(message);
  };
  if (data.type === "numina-version") reply({ type: "numina-version", version: VERSION, files: PRECACHE.length });
  else if (data.type === "numina-update") self.skipWaiting();
});
