// Hearth — the log’s template grammar and the daily flavor lines drawn from it.
// Classic scripts sharing one global scope; the load order in index.html is the old single file’s order and it matters.
// ---------- log grammar ----------
// each template: {c: cond(ctx)->bool, t: text with slots, w: weight}. Slots: {A} {B} {C} names, {rel} A–B relation, {spot} A's favourite spot, {sea} season, {wx} weather word, {ev} a remembered event, {age}
const WX=()=>storm?'the storm':rain?'the rain':wx==='snow'?'the snow':wx==='fog'?'the fog':isNight()?'the dark':dayFrac()<edges()[0]+.1?'the early light':dayFrac()>edges()[1]-.1?'the evening':wx==='overcast'?'the grey':'the sun';
const G=[
  // relationships
  {c:x=>x.b&&x.rel==='friend'&&x.night,t:'{A} and {B} sit late by the fire. Neither of them is saying much.'},
  {c:x=>x.b&&x.rel==='friend'&&x.ev,t:'{A} and {B} sit by the fire; {A} is telling the story of {ev} again.'},
  {c:x=>x.b&&x.rel==='friend'&&!x.night,t:'{A} and {B} share the shade at {spot} and talk about nothing in particular.'},
  {c:x=>x.b&&x.rel==='rival',t:'{A} and {B} disagree, again, about the right way to stack a woodpile.'},
  {c:x=>x.b&&x.rel==='rival'&&x.rain,t:'{A} says the rain is {B}\'s fault somehow. {B} does not dignify it.'},
  {c:x=>x.b&&x.rel==='rival'&&x.stubborn,t:'{A} will not be the first to speak to {B}. It has been three days.'},
  {c:x=>x.b&&x.rel==='partner',t:'{A} saves the softer bread for {B} without mentioning it.'},
  {c:x=>x.b&&x.rel==='partner'&&x.night,t:'{A} and {B} walk home together in {wx}, not hurrying.'},
  {c:x=>x.b&&x.rel==='partner'&&x.rain,t:'{A} holds a cloak over {B}\'s head all the way from the fields.'},
  {c:x=>x.b&&x.rel==='child',t:'{A} shows {B} how to tell a ripe ear from a green one. {B} is more interested in a beetle.'},
  {c:x=>x.b&&x.rel==='child'&&x.night,t:'{A} carries {B} home asleep from the fire.'},
  {c:x=>x.b&&x.rel==='parent',t:'{A} tries to walk exactly in {B}\'s footprints.'},
  {c:x=>x.b&&x.rel==='parent'&&x.dusk,t:'{A} sits on {B}\'s knee at dusk and asks where the sun goes.'},
  // gossipy
  {c:x=>x.gossipy&&x.b&&x.c,t:'{A} tells {B} something about {C} that {C} would rather stayed private.'},
  {c:x=>x.gossipy&&x.b,t:'{A} has a theory about why {B} was late this morning, and shares it widely.'},
  {c:x=>x.gossipy&&x.c&&x.b,t:'According to {A}, {B} and {C} were seen at {spot} together. Twice.'},
  {c:x=>x.gossipy,t:'{A} counts the loaves in the store and tells everyone the number.'},
  // restless / homesick / dreamy
  {c:x=>x.restless&&!x.night,t:'{A} walks the whole shore before breakfast and comes back no calmer.'},
  {c:x=>x.restless&&x.night,t:'{A} lies awake listening to the water and thinking about the far side of it.'},
  {c:x=>x.homesick,t:'{A} looks out to sea from {spot} and names the people who are not here.'},
  {c:x=>x.homesick&&x.rain,t:'{A} says the rain sounds like the rain at home. It sounds like rain.'},
  {c:x=>x.homesick&&x.b,t:'{A} tells {B} about a house that had a blue door. {B} has heard about the blue door.'},
  {c:x=>x.dreamy&&!x.night,t:'{A} stops halfway through a task to watch a cloud change its mind.'},
  {c:x=>x.dreamy&&x.night,t:'{A} counts the stars over the water and loses the count on purpose.'},
  {c:x=>x.dreamy&&x.b,t:'{A} tells {B} what the island will look like in a hundred years. {B} nods, kindly.'},
  // gentle / patient / stubborn / proud / brave / funny
  {c:x=>x.gentle&&x.b,t:'{A} notices {B} is tired and quietly takes the heavier basket.'},
  {c:x=>x.gentle&&x.graves,t:'{A} pulls the weeds from around the stones on the hill.'},
  {c:x=>x.gentle,t:'{A} sets a bit of grain out for the birds and pretends it was spilled.'},
  {c:x=>x.patient,t:'{A} sharpens the axe for a long time before using it once.'},
  {c:x=>x.patient&&x.b,t:'{A} explains a knot to {B} for the fourth time, no differently from the first.'},
  {c:x=>x.stubborn,t:'{A} finishes the row in {wx} because {A} said the row would be finished.'},
  {c:x=>x.stubborn&&x.b,t:'{B} suggests a shorter path. {A} takes the long one.'},
  {c:x=>x.proud,t:'{A} will not be seen pulling weeds, and takes the axe instead.'},
  {c:x=>x.proud&&x.b,t:'{A} corrects {B}\'s grip on the hammer. It was fine.'},
  {c:x=>x.brave&&x.rain,t:'{A} goes down to the water in {wx} with a line and comes back wet and pleased.'},
  {c:x=>x.brave,t:'{A} climbs the grey rocks to see what is on the other side. Sea, mostly.'},
  {c:x=>x.funny&&x.b,t:'{A} does an impression of {B} that {B} pretends not to enjoy.'},
  {c:x=>x.funny&&x.rain,t:'{A} announces that {wx} is a good sign, and refuses to say of what.'},
  {c:x=>x.funny&&x.c&&x.b,t:'{A} makes {B} laugh so hard that {C} comes over to see what happened.'},
  // weather / season / general
  {c:x=>x.storm,t:'The wind takes the smoke sideways. {A} ties down the woodpile.'},
  {c:x=>x.rain&&!x.night,t:'{A} stands under the eaves and watches {wx} fill the ruts.'},
  {c:x=>x.sea==='spring',t:'{A} finds the first green shoots and tells everyone, in case they had not seen.'},
  {c:x=>x.sea==='summer'&&!x.night,t:'{A} lies in the long grass at {spot} through the hot part of the day.'},
  {c:x=>x.sea==='autumn',t:'{A} smells woodsmoke and cold on the wind and says the year is turning.'},
  {c:x=>x.sea==='winter'&&x.night,t:'{A} feeds the fire twice before sleeping. The nights are long now.'},
  {c:x=>x.elder,t:'{A} sits by the fire and tells anyone who passes that the winters used to be worse.'},
  {c:x=>x.elder&&x.b,t:'{A} tells {B} how the first house was raised. {B} has heard it. {B} listens anyway.'},
  {c:x=>x.kid&&x.b,t:'{A} follows {B} around the fields asking why.'},
  {c:x=>x.kid,t:'{A} finds a crab at {spot} and names it.'},
  {c:x=>x.ev&&x.b,t:'{B} asks {A} about {ev}. {A} tells it a little differently each time.'},
  {c:x=>x.hungry&&!x.kid,t:'{A} pretends not to be hungry so the others will eat.'},
  {c:x=>true,t:'{A} finds a smooth blue stone at {spot} and keeps it.',w:.5},
  {c:x=>!x.kid&&!x.knows,t:'{A} hums an old song while working. Nobody knows the words.',w:.5},
  {c:x=>x.b&&!x.kid,t:'{A} and {B} argue about whether the wind smells like rain.',w:.5},
  // weather fronts, seasons, store, tide (sprint 2)
  {c:x=>x.fog,t:'{A} walks into the fog and comes back out of it somewhere else, surprised.'},
  {c:x=>x.fog&&x.b,t:'{A} calls to {B} through the fog and gets an answer from the wrong direction.'},
  {c:x=>x.fog&&x.homesick,t:'{A} says a fog like this could hide a whole coast. {A} looks for one anyway.'},
  {c:x=>x.snow&&!x.kid,t:'{A} holds out a hand and lets the snow settle on it, and does not brush it off.'},
  {c:x=>x.snow&&x.kid,t:'{A} tries to catch snow on the tongue and reports on the taste.'},
  {c:x=>x.snow&&x.b,t:'{A} and {B} stamp the path down to the water so it will still be there tomorrow.'},
  {c:x=>x.thunder,t:'{A} counts between the flash and the sound, and says it is getting closer.'},
  {c:x=>x.thunder&&x.brave,t:'{A} stands in the doorway watching the lightning while everyone else pretends not to.'},
  {c:x=>x.thunder&&x.kid&&x.b,t:'{A} climbs into {B}\'s lap at the first crack of thunder and stays there.'},
  {c:x=>x.thunder&&x.b&&x.rel==='rival',t:'{A} and {B} end up under the same roof for the storm and manage not to speak of it.'},
  {c:x=>x.ice&&!x.kid,t:'{A} tests the ice on the shallows with one foot, then the other, then walks back.'},
  {c:x=>x.ice&&x.kid,t:'{A} slides across the frozen shallows and falls, and does it again.'},
  {c:x=>x.hungry&&x.b,t:'{A} and {B} both say they ate already. Neither did.'},
  {c:x=>x.hungry&&x.gossipy,t:'{A} has worked out exactly how many days the store will last, and tells everyone.'},
  {c:x=>x.hungry&&x.patient,t:'{A} makes the thin soup last by stirring it for a long time.'},
  {c:x=>x.hungry&&x.kid&&x.b,t:'{B} gives {A} the larger half and says it was the smaller.'},
  // phase 6: the short winter, from the inside
  {c:x=>x.rations,t:'{A} eats the ration and then sits on with the empty bowl a while, out of habit rather than hope.'},
  {c:x=>x.rations&&x.night,t:'The store gets counted again after dark. Nobody asked {A} to; {A} would rather know than sleep.'},
  {c:x=>x.rations&&x.kid,t:'{A} has worked out that the grown ones are eating less than they say, and has not worked out what to do about it.'},
  {c:x=>x.rations&&x.b&&x.gossipy,t:'{A} tells {B} what the store was at this time last year. {B} did not ask and does not want to know.'},
  {c:x=>x.short&&x.b,t:'{A} says old people do not need much, without being asked. {B} does not believe a word of it.',w:1.6},
  {c:x=>x.short&&x.night,t:'{A} takes the plate last and takes the least off it, and has an answer ready that nobody uses.'},
  {c:x=>x.raided&&x.rel==='rival',t:'{A} and {B} pass each other at the store and neither of them looks up.',w:1.6},
  {c:x=>x.feudp,t:'{A} takes the long way round to the fields rather than pass {B}\'s door. It costs ten minutes every morning, and {A} pays it.',w:1.6},
  {c:x=>x.feudp&&x.hall,t:'{A} waits outside the hall until {B} has left it. Everyone inside knows exactly what the wait is for.'},
  {c:x=>x.feudp&&x.night,t:'{A} and {B} keep their fires on opposite sides of the village. Each can see the other\'s from the door, and does not look.'},
  {c:x=>x.feudkid,t:'{A} has never been told a word about it, and knows to the yard where the line runs, the way children do.',w:1.2},
  {c:x=>x.rations&&x.stone,t:'{A} stands at the quiet stone a long time and asks it for nothing in particular, which is new.'},
  {c:x=>x.sea==='autumn'&&x.b&&!x.night,t:'{A} and {B} carry the last baskets to the store and stand looking at it, weighing the winter.'},
  {c:x=>x.sea==='autumn'&&x.leaves,t:'{A} walks through the fallen leaves on purpose, for the sound.'},
  {c:x=>x.sea==='winter'&&!x.night,t:'{A} feeds the fire and looks at the woodpile and does the arithmetic.'},
  {c:x=>x.sea==='winter'&&x.night&&x.b,t:'{A} and {B} sleep close for the warmth and say it is only for the warmth.'},
  {c:x=>x.sea==='spring'&&x.b&&x.blossom,t:'{A} shakes a blossoming branch over {B} and pretends it was the wind.'},
  {c:x=>x.sea==='summer'&&x.night,t:'{A} sleeps outside because the house holds the heat, and wakes wet with dew.'},
  {c:x=>x.sea==='summer'&&!x.night&&x.b,t:'{A} and {B} wade out to the knees at noon and stand there, saying nothing about work.',w:.5},
  {c:x=>x.lowtide&&!x.night,t:'{A} walks out on the wet sand at low tide and finds a shell the size of a hand.',w:.5},
  {c:x=>x.hightide&&x.kid,t:'{A} draws a line in the sand and waits for the tide to take it.'},
  {c:x=>x.overcast,t:'{A} says it will rain. It does not rain. {A} says it will rain tomorrow.'},
  // the town (sprint 3)
  {c:x=>x.market&&!x.night&&x.b,t:'{A} and {B} meet at the market and settle nothing about the price of anything.'},
  {c:x=>x.market&&x.gossipy,t:'{A} holds court at the market and knows who has been buying what, and why.'},
  {c:x=>x.market&&x.kid,t:'{A} runs between the stalls and is given a broken biscuit at each one.'},
  {c:x=>x.mill&&x.dreamy,t:'{A} watches the mill sail go round until it is not clear who is turning whom.'},
  {c:x=>x.mill&&x.kid&&x.b,t:'{B} lifts {A} to touch the mill sail as it passes, and {A} screams, happily.'},
  {c:x=>x.well&&x.b,t:'{A} and {B} meet at the well and take a long time about a short bucket.'},
  {c:x=>x.well&&x.hungry,t:'{A} drinks at the well and calls it a meal.'},
  {c:x=>x.hall&&x.night,t:'{A} sits in the hall after the others have gone and listens to the bell rope creak.'},
  {c:x=>x.hall&&x.b&&x.rel==='rival',t:'{A} and {B} sit on opposite benches in the hall and address the room, not each other.'},
  {c:x=>x.light&&x.night,t:'{A} counts the beam going round from the doorstep. Nine, and then nine again.'},
  {c:x=>x.light&&x.homesick&&x.night,t:'{A} watches the lighthouse sweep the dark and wonders if anyone out there sees it.'},
  {c:x=>x.hut&&x.b,t:'{A} mends a net on the hut steps while {B} tells the story of the one that was bigger.'},
  {c:x=>x.smoke,t:'{A} comes back from the smokehouse smelling of it and denies it.'},
  {c:x=>x.bridge&&x.kid,t:'{A} drops sticks off the bridge and races them to the other side.'},
  {c:x=>x.bridge&&x.b,t:'{A} and {B} stop halfway across the bridge, which is where the talking happens.'},
  {c:x=>x.trader&&x.b,t:'{A} and {B} stand on the shore pretending not to be waiting for the trader\'s boat.'},
  {c:x=>x.trader&&x.gossipy,t:'{A} has already asked the trader three questions and answered two of them.'},
  {c:x=>x.road&&!x.night,t:'{A} walks the path to the fields without looking down. It knows the way.',w:.35},
  {c:x=>x.named&&x.homesick,t:'{A} says the name of {village} out loud, once, to see how it sounds. It sounds all right.',w:.4},
  {c:x=>x.named&&x.elder,t:'{A} remembers when {village} was four people and a fire, and says so, and is not contradicted.'},
  // wildlife and the wider world (sprint 4)
  {c:x=>x.deer&&x.kid,t:'{A} sees a deer at the edge of the trees and stands very still, and it goes anyway.'},
  {c:x=>x.deer&&x.gentle,t:'{A} leaves the last of the windfalls under the trees for the deer, and says the birds must have had them.'},
  {c:x=>x.deer&&x.brave&&x.b,t:'{A} tells {B} the deer are getting bolder. {B} says it is {A} who is getting slower.'},
  {c:x=>x.gulls&&x.funny,t:'{A} does the gulls, all of them, in order. The gulls do not think it is funny either.'},
  {c:x=>x.gulls&&x.hut&&x.b,t:'{A} and {B} eat on the hut steps and lose half of it to the gulls, who were counting on it.'},
  {c:x=>x.gulls&&x.gossipy,t:'{A} says the gulls know when the boat is coming in before anyone, and is right, and is insufferable about it.'},
  {c:x=>x.rabbits&&x.farms&&!x.night,t:'{A} chases a rabbit out of the field and it comes back in behind {A}, and this goes on for a while.'},
  {c:x=>x.rabbits&&x.kid&&x.b,t:'{A} shows {B} where the rabbits come out at dusk, and they both lie in the grass to watch, and fall asleep.'},
  {c:x=>x.fox&&x.night,t:'Something small screams once out in the dark. {A} says fox, and it was.'},
  {c:x=>x.fox&&x.night&&x.b,t:'{A} sees the fox cross the path in the light of the fire, and tells {B}, who says there is no fox, and there is.'},
  {c:x=>x.fireflies&&x.kid,t:'{A} runs after the little lights over the grass with cupped hands and comes back with nothing, and is delighted.'},
  {c:x=>x.fireflies&&x.dreamy,t:'{A} sits in the long grass with the fireflies and does not come in until they have gone out.'},
  {c:x=>x.fireflies&&x.b&&x.rel==='partner',t:'{A} and {B} watch the fireflies from the doorstep and do not need to say anything about them.'},
  {c:x=>x.geese&&x.homesick,t:'The geese go over in a long V, going the way {A} came from. {A} watches them out of sight.'},
  {c:x=>x.geese&&x.kid,t:'{A} counts the geese going over and gets a different number every time.'},
  {c:x=>x.geese&&x.elder,t:'{A} hears the geese before anyone sees them and says it will be a hard winter. {A} says this every year.'},
  {c:x=>x.whale&&x.dreamy,t:'Far out, something breathes. {A} sees the spout go up and does not tell anyone, and keeps it.'},
  {c:x=>x.whale&&x.b,t:'{A} points out to sea and by the time {B} looks it is gone. {B} believes {A}, mostly.'},
  {c:x=>x.whale&&x.elder,t:'{A} says the big fish come past this time of year, and always have, and always will.'},
  {c:x=>x.fish&&x.kid,t:'{A} lies on the sand and watches the fish shadows in the shallows go where they go.'},
  {c:x=>x.fish&&x.patient,t:'{A} stands in the shallows very still until the fish forget about the feet.'},
  {c:x=>x.far&&x.restless&&!x.fog,t:'{A} looks at the far island on the horizon for a long time. It has not moved.'},
  {c:x=>x.far&&x.homesick&&x.dusk,t:'At dusk the far island is a darker line on the dark. {A} wonders who lights fires there, if anyone.'},
  {c:x=>x.far&&x.kid&&x.b,t:'{A} asks {B} what is on the far island. {B} says giants. {A} thinks about this for a long time.'},
  {c:x=>x.far&&x.dreamy&&x.b,t:'{A} tells {B} the far island is where the weather is kept. {B} lets it stand.'},
  {c:x=>x.far&&x.brave&&!x.voyaged,t:'{A} says someone should take a boat out to the far island and see. Nobody says who.'},
  {c:x=>x.farn&&x.dusk,t:'{A} stands at the top of the beach looking at {farn} until the light goes, and does not say what about.'},
  {c:x=>x.farn&&x.b&&x.gossipy,t:'{A} has worked out, out loud, to {B}, exactly how long it would take to row to {farn}. The number changes each time.'},
  {c:x=>x.away&&x.b,t:'{A} and {B} both look out to the far island and neither of them says the name that is on both their minds.'},
  {c:x=>x.away&&x.gossipy,t:'{A} has three theories about what {voy} found on the far island, and shares them, and prefers the worst one.'},
  {c:x=>x.stayed&&x.night&&!x.fog,t:'There is a light on the far island tonight. It could be anyone. Everyone at the fire says it is {voy}.'},
  {c:x=>x.stayed&&x.homesick,t:'{A} looks out at the far island and says {voy} chose it, and that some people do.'},
  {c:x=>x.ruin&&x.kid,t:'{A} climbs the old stones and is told to get down, and gets down, and climbs them again.'},
  {c:x=>x.ruin&&x.elder&&x.b,t:'{A} tells {B} the old stones were here before the trees. {B} asks how {A} knows. {A} was told, by someone who was told.'},
  {c:x=>x.ruin&&x.gossipy,t:'{A} has worked out that the old stones were put up by giants, and cannot be talked out of it.'},
  {c:x=>x.ruin&&x.dreamy&&x.night,t:'{A} sits among the old stones after dark to see if anything happens. Nothing happens, and it is very good.'},
  {c:x=>x.ruin&&x.brave,t:'{A} lifts one of the fallen stones and cannot, and pretends that was not what {A} was doing.'},
  {c:x=>x.ruin&&x.gentle,t:'{A} pulls the ivy back from the old stones so that whoever set them would know they were seen.'},
  {c:x=>x.ruin&&x.b&&x.rel==='rival',t:'{A} and {B} disagree about who built the old stones. Neither of them was there.'},
  // the watcher's blessings (sprint 5)
  {c:x=>x.spring&&!x.night,t:'{A} kneels at the spring and drinks straight out of it, and says it tastes like the inside of a stone.'},
  {c:x=>x.spring&&x.b,t:'{A} and {B} disagree, pleasantly, about whether the spring was always there. It was not.'},
  {c:x=>x.spring&&x.kid,t:'{A} floats a leaf on the pond and follows it round the edge until it sinks.'},
  {c:x=>x.spring&&x.dreamy&&x.night,t:'{A} sits by the new water after dark and listens to it doing nothing in particular.'},
  {c:x=>x.cloudrain,t:'One cloud is raining, out of a whole sky that is not. {A} goes and stands under it on purpose.'},
  {c:x=>x.cloudrain&&x.gossipy,t:'{A} has an explanation for rain falling on one field and nowhere else. It is wrong, and it is very confident.'},
  {c:x=>x.story&&x.night,t:'Long after the story {A} is still awake, fitting the pieces of it together a different way.'},
  {c:x=>x.story&&x.kid&&x.b,t:'{A} asks {B} to tell the part about the boat again. {B} tells it again, longer.'},
  {c:x=>x.dreamt&&x.b,t:'{A} tries to tell {B} a dream, gets it wrong twice, and starts again from the beginning.'},
  {c:x=>x.dreamt&&x.elder,t:'{A} says the dreams on this island are not like the dreams at home, and will not be drawn on it.'},
  // what the hands learn (sprint 10)
  {c:x=>x.crf===0&&x.cxpv>.3&&!x.night,t:'{A} pulls one weed on the way past the field, without breaking stride or conversation.'},
  {c:x=>x.crf===1&&x.cxpv>.3,t:'{A} lays a hand flat on a trunk in passing, the way you greet someone you know.'},
  {c:x=>x.crf===2&&x.cxpv>.3&&!x.night,t:'{A} looks at the sea once at first light and says what it will do all day, and is mostly right.'},
  {c:x=>x.crf===3&&x.cxpv>.3,t:'{A} stops under a doorway, presses up on the lintel with one thumb, and moves on satisfied.'},
  {c:x=>x.crf===4&&x.cxpv>.3,t:'{A} straightens the sacks in the store so the count can be seen at a glance. Nobody asked.'},
  {c:x=>x.crf>=0&&x.cxpv>.5&&x.b&&x.rel==='friend',t:'{B} asks {A} how {A} always knows. {A} says you just watch long enough, which is no help at all.'},
  {c:x=>x.cxpv>=1,t:'{A} does the hard part of the work slowly, on purpose, so the ones watching can see how it goes.',w:.7},
  {c:x=>x.cxpv>=1&&x.b&&x.rel==='rival',t:'{B} would never ask {A} for help with it. {B} watches how {A} does it, though. Everyone watches how {A} does it.',w:.7},
  {c:x=>x.dryg&&!x.rain&&!x.night,t:'The dust stands behind every footstep on the field path. Everyone is watching the sky and saying so.'},
  {c:x=>x.dryg&&x.well,t:'There is a line at the well before the light is even properly up.'},
  {c:x=>x.mill&&!x.night&&!x.storm,t:'{A} comes down the mill path dusted white to the elbows and denies having tried the flour, unconvincingly.',w:.7},
  {c:x=>x.orchard&&x.sea==='spring',t:'The orchard is in blossom, all three trees at once, and people take the long way round just to pass it.'},
  {c:x=>x.orchard&&x.kid&&x.sea==='autumn',t:'{A} is up one of the orchard trees. The rule about the orchard trees is recited from below, without effect.'},
  {c:x=>x.hives&&x.sea==='summer',t:'{A} stands near the hives listening to the working hum and says it is a good sound for a village to have.'},
  {c:x=>x.swingw&&x.kid,t:'{A} swings until the rope creaks and the sky tilts, and calls out to be watched, and is watched.'},
  {c:x=>x.ringw&&x.night,t:'The fire sits low in its ring of stones, banked and kept, and the stones hold the heat long after.'},
  {c:x=>x.bench&&x.elder,t:'{A} sits on the bench at the lighthouse a long while, not waiting for anything. Whoever the bench was for, it was for this.'},
  {c:x=>x.oldhouse,t:'Someone has left a candle burning in the old house among the stones. Nobody says who, and nobody is troubled by it.'},
  {c:x=>x.oldhouse&&x.elder&&x.b,t:'{A} tells {B} that whoever set the old stones would be glad of the roof. {B} asks how anyone would know. {A} says you would know.'},
  {c:x=>x.racks&&x.gulls,t:'The gulls have opinions about the drying racks and state them all day. The racks stay shut.'},
  {c:x=>x.boat2&&!x.night&&!x.storm,t:'Both boats are out past the shallows at once, and from the shore {village} looks, briefly, like a port.'},
  // the year's fortunes, the ways, and the quiet stone (sprint 11)
  {c:x=>x.drought,t:'The stream is down to a whisper and the field path stands in dust. {A} taps the rain barrel out of habit, and it answers hollow.'},
  {c:x=>x.drought&&x.kid,t:'{A} asks when the rain is coming back. Nobody answers quickly enough, and {A} files that away.'},
  {c:x=>x.drought&&x.well,t:'The line at the well starts before the light now. Nobody pushes in. Everyone counts the buckets ahead of them.'},
  {c:x=>x.hardw,t:'The cold has got into the walls and set up house. {A} wears everything {A} owns, in layers, and rattles slightly when walking.'},
  {c:x=>x.hardw&&x.b,t:'{A} and {B} split the last of the split wood, and neither will take the bigger share, which takes a while.'},
  {c:x=>x.feverA&&!x.sick,t:'{A} carries broth to the houses where the fever is and leaves it on the steps, and knocks, and does not wait.'},
  // the sickness, and the sitting up with it (phase 6)
  {c:x=>x.sick&&!x.abed,t:'{A} is up and dressed and insisting on working, and is walked firmly back to bed by whoever is nearest.'},
  {c:x=>x.abed,t:'{A} sleeps most of the day and is furious about the rest of it, and asks twice what got done without them.'},
  {c:x=>x.abed&&x.nursed,t:'Somebody has left a cup by {A}, covered with a plate to keep the warm in. {A} does not know whose plate it is.'},
  {c:x=>x.abed&&!x.nursed&&x.night,t:'There is a light in the house where {A} is, later than there should be, and nobody in it but {A}.'},
  {c:x=>x.illw&&!x.sick&&x.hall,t:'The hall smells of broth and wet wool and is warmer than anywhere else on the island, and nobody is calling it what it is.'},
  {c:x=>x.illw&&!x.sick&&x.b,t:'{A} asks {B} how the ones in bed are, and gets the number rather than the names, which is how {B} is managing it.'},
  {c:x=>x.illw&&!x.sick&&x.kid,t:'{A} has been told to keep away from the houses where it is, and does, and stands at exactly the distance the telling allowed.'},
  {c:x=>x.wellp&&!x.sick,t:'{A} has had it already and says so freely, and goes in and out of the sick house like it is nothing, and for {A} it is.'},
  {c:x=>x.shoalA&&!x.night,t:'The water past the shallows has been silver-backed since morning. Even {A} takes a line down, and even {A} catches.'},
  {c:x=>x.sail&&!x.night&&!x.storm,t:'The boat goes out under its little sail now and is back before the light goes, and the rowing songs are turning into sailing songs.'},
  {c:x=>x.plough&&!x.night,t:'{A} walks the ploughed rows just to look at them: long and clean, like handwriting that finally settled down.'},
  {c:x=>x.kiln,t:'{A} taps a fired pot with one knuckle in passing, for the ring of it. Everyone does this now. Nobody has said why.'},
  {c:x=>x.book&&x.elder,t:'{A} asks for the book of days to be opened to an argument from two winters ago, and is proven right, and is gracious about it for nearly an hour.'},
  {c:x=>x.book&&x.kid,t:'{A} is shown the line in the book of days where {A} was born, and reads it with one finger, twice.'},
  {c:x=>x.stone&&x.kid,t:'{A} tells the quiet stone a secret, cupped hands against the cold of it, in case something is listening. Something is.'},
  {c:x=>x.stone&&!x.night,t:'There is something small in the hollow at the foot of the quiet stone again this morning. Nobody saw it left. Nobody moves it.'},
  {c:x=>x.stone&&x.faithHi&&x.elder,t:'{A} says you can live a whole life on an island like this and never once catch it in the act of being kind. That, says {A}, is how you know.'},
  {c:x=>x.stone&&x.b&&x.rel==='rival',t:'{A} and {B} arrive at the quiet stone at the same moment, and take turns, in silence, and leave in different directions.'},
  // what is handed down, and how the stories grow (sprint 12)
  {c:x=>x.keeps,t:'{A} takes {thing} out in a quiet moment, turns it over twice, and puts it away again.',w:.8},
  {c:x=>x.keeps&&x.night,t:'{A} sets {thing} where the firelight can find it, and sits with it being older than everyone in the room.'},
  {c:x=>x.keeps&&x.b,t:'{B} asks to hold {thing}, and holds it carefully, and hands it back a little changed.'},
  {c:x=>x.keeps&&x.kid&&x.b,t:'{B} shows {A} {thing} and says where it came from. {A} asks to hear where it came from again.'},
  {c:x=>x.shelf,t:'Somebody has dusted the shelf in the hall again, and set what waits there a little straighter.',w:.7},
  {c:x=>x.shelf&&x.kid,t:'{A} is lifted up to see the shelf in the hall, and reaches, and is lowered again, unrepentant.'},
  {c:x=>x.legend&&x.kid&&x.b,t:'{A} asks {B} for the story of {leg}, the long way, with all the grown parts in.'},
  {c:x=>x.legend&&x.elder,t:'{A} tells {leg} the old way, the short true way, and is outvoted.'},
  {c:x=>x.legend&&x.gossipy,t:'{A} adds a small detail to the story of {leg} that was not in it yesterday, and by evening it always was.'},
  // the named ground (sprint 13): where the grown stories happen
  {c:x=>x.lore,t:'{A} takes the long way round past {lore}, the way everyone does now, without ever deciding to.',w:.7},
  {c:x=>x.lore&&x.kid&&x.b,t:'{A} makes {B} come and stand at {lore} for the telling, because that is where it happens, and stories go better standing in them.'},
  {c:x=>x.lore&&x.elder,t:'{A} remembers when {lore} was a stretch of ground like any other. It is not any more, and {A} was there when it stopped.'},
  {c:x=>x.lore&&x.dreamy&&!x.night,t:'{A} stands at {lore} fitting the story over the ground. The story has outgrown it. {A} decides the ground is what is wrong.'},
  // the stones the walks leave (sprint 14)
  {c:x=>x.cairn,t:'{A} passes {lore} and touches the top stone of the little pile there, the way everyone does now, without breaking stride.',w:.7},
  {c:x=>x.cairn&&x.kid,t:'{A} counts the stones at {lore} and reports the number, which is the number of times anyone has bothered. It is a good number.'},
  {c:x=>x.cairn&&x.elder&&x.b,t:'{A} tells {B} which stone at {lore} is {A}\'s. It is not possible to know that. {A} knows it anyway.'},
  // the island talks to itself (sprint 16): named years, songs, news on foot, the sky's occasions, the children's games
  {c:x=>x.yrname&&x.elder,t:'{A} still calls last year {yrname}, and will for the rest of {A}\'s life.'},
  {c:x=>x.yrname&&x.kid&&x.b,t:'{A} asks {B} why it is called {yrname}. {B} starts at the beginning.'},
  {c:x=>x.knows&&!x.night,t:'{A} hums the song of {song} over the work, half under the breath, and the work keeps the time.'},
  {c:x=>x.knows&&x.kid,t:'{A} sings the song of {song} out at the tideline, all the verses, with the hard word in the middle taken carefully.'},
  {c:x=>x.songy&&x.b&&x.rel==='partner',t:'{A} hums the first line of the song of {song} and {B} takes the second without looking up.'},
  {c:x=>x.songlost&&x.elder,t:'{A} says there was a tune to that story once, and hums three notes of nothing, and lets it go.'},
  {c:x=>x.news&&x.b,t:'{A} has news and has not told {B} yet, and is enjoying the not telling almost too much to end it.'},
  {c:x=>x.starday&&x.dreamy,t:'{A} is still thinking about the star that fell, and where fallen things land, and whether you could walk there.'},
  {c:x=>x.starday&&x.kid&&x.b,t:'{A} tells {B} about the star that fell last night, making it bigger. It was big enough.'},
  {c:x=>x.aurora&&x.night,t:'The sky over the island is moving in slow green folds. Nobody goes in until it has finished.'},
  {c:x=>x.aurora&&x.night&&x.elder,t:'{A} says the sky did this the winter {A} was small, and that it means nothing, and watches it to the end anyway.'},
  {c:x=>x.rb,t:'A rainbow stands over the island with both feet in the sea. Work does not exactly stop, and does not exactly go on either.'},
  {c:x=>x.snowman,t:'The snowman has been given somebody\'s hat. Nobody has missed it yet, and everybody knows whose it is.',w:.7},
  {c:x=>x.snowman&&x.kid,t:'{A} reports to the snowman on the state of the village, which the snowman receives with composure.'},
  {c:x=>x.gravev&&x.elder,t:'{A} says the moss on the most-visited stone on the hill is the hill\'s own answer, and does not say to what.'},
  {c:x=>x.gravev&&x.kid,t:'{A} asks why everyone stops at {gv}\'s stone before the others. Nobody has one answer, so {A} is given several.'},
  {c:x=>x.gvn>=30&&x.kid,t:'{A} has been keeping count: {gv}\'s stone has been stood at {gvn} times that anyone saw. {A} says the number as if it were a secret.',w:.7},
];
const ARRIVED=p=>pick([`${p.name} rowed in out of nowhere and asked to stay, and stayed.`,
  `${p.name} came ashore with everything ${p.name} owned in one bag, and was given bread before any questions.`,
  `A boat put in on the sand and ${p.name} got out of it, and never quite got back in.`,
  `${p.name} arrived off the water in the ${sea()}, and by evening was carrying something for somebody.`]);
function eventLabel(){if(!events.length)return null;const e=events[(R()*events.length)|0];return e.label}
function flavor(){const cand=people.filter(p=>!p.dead);if(!cand.length)return;
  // gossipy islanders are picked more often
  const wts=cand.map(p=>has(p,'gossipy')?2.2:1);let s=wts.reduce((a,b)=>a+b,0),r=R()*s,a=cand[0];for(let i=0;i<cand.length;i++){r-=wts[i];if(r<=0){a=cand[i];break}}
  const rel=a.rels.length&&R()<.75?a.rels[(R()*a.rels.length)|0]:null;const b=rel?byName(rel.who):(cand.length>1?pick(cand.filter(p=>p!==a)):null);
  const c=cand.length>2?pick(cand.filter(p=>p!==a&&p!==b)):null;
  const td=tide(),gvTop=graves.reduce((m,g2)=>(g2.vn||0)>(m?m.vn||0:0)?g2:m,null); /* phase 7: the most-visited stone, by count, so the number feeds a line and not only pixels */
  const ctx={a,b,c,rel:rel?rel.k:null,night:isNight(),dusk:isDusk(),rain,storm,thunder:storm,market:hasB('market'),mill:hasB('mill'),well:hasB('well'),hall:hasB('hall'),light:hasB('light'),hut:hasB('hut'),smoke:hasB('smoke'),bridge:hasB('bridge'),trader:!!trader,road:roadV>0,named:!!village,deer:wild.some(w=>w.k==='deer'),rabbits:wild.some(w=>w.k==='rabbit'),farms:farms.length>0,fox:wild.some(w=>w.k==='fox'),gulls:gulls.length>0,fireflies:flies.length>0,geese:geeseDay===dayCount,whale:!!whale||whaleDay===dayCount,fish:fishSh.length>0&&!frozen,far:!!farIsle,farn:farKnown(),voyaged:!!voyage,away:!!voyage&&voyage.st==='away',stayed:!!voyage&&voyage.st==='stayed',ruin:!!ruin&&ruinSeen>0,spring:springs.length>0,story:storyDay===dayCount,dreamt:dreamAny===dayCount,cloudrain:clouds.some(c=>c.r>0),fog:wx==='fog',snow:wx==='snow',overcast:wx==='overcast',ice:frozen,hungry:hunger>.25,rations:!!want,short:!!a.short,raided:!!(want&&want.raid),feudp:!!(b&&feudWith(a)===b),feudkid:!!(feud&&isKid(a)&&feudSide(a)),leaves:seaDay()>=2,blossom:seaDay()<=3,lowtide:td<-.6,hightide:td>.6,sea:seasonOf(dayCount),ev:eventLabel(),graves:graves.length>0,elder:isElder(a),kid:isKid(a),
    crf:a.craft,cxpv:a.cxp||0,orchard:hasW('orchard'),hives:hasW('hives'),swingw:hasW('swing'),ringw:hasW('ring'),bench:hasW('bench'),oldhouse:hasW('ruin3'),racks:hasW('racks'),boat2:hasW('boat2'),dryg:dry01>.6,
    drought:arcK()==='drought',hardw:arcK()==='longwinter',feverA:arcK()==='fever',shoalA:arcK()==='shoal',sick:!!a.sick,abed:a.task==='abed',illw:!!ill,nursed:a.nursed>=dayCount-1,wellp:wellNow(a),sail:hasWay(0),plough:hasWay(1),kiln:hasWay(2),book:hasWay(3),stone:hasW('shrine'),faithHi:faith>=.5,
    keeps:thingsOf(a.name).length>0,shelf:hasB('hall')&&things.some(t=>!t.holder),legend:chron.some(e=>e.gr),lore:spots.some(s=>s.lore),cairn:spots.some(s=>s.lore&&(loreN[s.k]||0)>=2),
    yrname:(()=>{const yn=yearName(yearOf(dayCount)-1);return yn&&yn!=='a quiet year'?yn:null})(),
    knows:songs.some(sg=>!sg.lost&&sg.kn.includes(a.name)),songy:songs.some(sg=>!sg.lost),songlost:songs.some(sg=>sg.lost),
    news:!!(a.heard&&a.heard.d>=dayCount-3),starday:starDay===dayCount,aurora:auroraNight()&&wx==='clear',rb:rbUntil>time,
    snowman:snowmen.length>0,gravev:graves.some(g2=>(g2.vn||0)>=12),gvn:gvTop?gvTop.vn||0:0};
  for(const t of TRAITS)ctx[t]=has(a,t);
  const ka=thingsOf(a.name),grown=chron.filter(e=>e.gr),legLbl=grown.length?grown[(R()*grown.length)|0].label:null;
  const loreSp=spots.filter(s=>s.lore),loreL=loreSp.length?loreSp[(R()*loreSp.length)|0].l:null;
  const sgs=songs.filter(sg=>!sg.lost&&chron[sg.ci]),songL=sgs.length?chron[sgs[(R()*sgs.length)|0].ci].label:null;
  const ok=G.filter(t=>t.c(ctx)&&(usedTpl.get(t)||0)<dayCount);if(!ok.length)return;
  const wt=ok.map(t=>t.w||1);s=wt.reduce((x,y)=>x+y,0);r=R()*s;let tpl=ok[0];for(let i=0;i<ok.length;i++){r-=wt[i];if(r<=0){tpl=ok[i];break}}
  const txt=tpl.t.replace(/{A}/g,B(a)).replace(/{B}/g,b?B(b):'someone').replace(/{C}/g,c?B(c):'someone').replace(/{spot}/g,a.spot.l).replace(/{sea}/g,ctx.sea).replace(/{wx}/g,WX()).replace(/{ev}/g,ctx.ev||'the first landing').replace(/{village}/g,V()).replace(/{voy}/g,voyage?voyage.name:'someone').replace(/{farn}/g,farN()).replace(/{thing}/g,ka.length?ka[0].n:'a small thing').replace(/{leg}/g,legLbl||'the first landing').replace(/{lore}/g,loreL||'the shore').replace(/{song}/g,songL||'the landing').replace(/{yrname}/g,ctx.yrname||'the year that was').replace(/{gv}/g,gvTop?gvTop.name:'someone').replace(/{gvn}/g,String(ctx.gvn));
  if(say(txt))usedTpl.set(tpl,dayCount)}
